/*
* generated by Xtext
*/
package v1.quiz.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class QuizOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
