/*
* generated by Xtext
*/
package v1.quiz.ui.contentassist;

import v1.quiz.ui.contentassist.AbstractQuizProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QuizProposalProvider extends AbstractQuizProposalProvider {

}
