/*
 * generated by Xtext
 */
package v1.quiz.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class QuizExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return v1.quiz.ui.internal.QuizActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return v1.quiz.ui.internal.QuizActivator.getInstance().getInjector("v1.quiz.Quiz");
	}
	
}
