/*
 * generated by Xtext
 */
package v1.quiz;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QuizRuntimeModule extends v1.quiz.AbstractQuizRuntimeModule {

}
