/*
 * generated by Xtext
 */
package v1.quiz.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QuizUiModule extends v1.quiz.ui.AbstractQuizUiModule {
	public QuizUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
