/*
* generated by Xtext
*/
package v1.quiz.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import v1.quiz.services.QuizGrammarAccess;

public class QuizParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QuizGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected v1.quiz.parser.antlr.internal.InternalQuizParser createParser(XtextTokenStream stream) {
		return new v1.quiz.parser.antlr.internal.InternalQuizParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "QuizGame";
	}
	
	public QuizGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QuizGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
