/*
* generated by Xtext
*/
package v1.quiz;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class QuizUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return v1.quiz.ui.internal.QuizActivator.getInstance().getInjector("v1.quiz.Quiz");
	}
	
}
